<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>config</string>
		<string>config-debug</string>
		<string>config-release</string>
		<string>config-test</string>
		<string>resource</string>
		<string>versions</string>
		<string>dependencies</string>
	</array>
	<key>name</key>
	<string>Total.js Configuration File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^[\/a-zA-Z0-9:\.\-\_]+)(?=([^:]|[^-->]))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((\s:|\s-->).*?$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\/\/.*?$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>($)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.basic</string>
	<key>uuid</key>
	<string>17994EC8-6B1D-11D9-AC3A-000D93589AF6</string>
</dict>
</plist>